# Development environment configuration
# Extends the base docker-compose.yml
version: '3.8'

services:
  backend:
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - DATABASE_URL=postgresql://dev_user:dev_pass@postgres:5432/dev_db
    command: bun run dev
    depends_on:
      - postgres
      - redis

  frontend:
    ports:
      - "3000:5173"
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:3001
    command: bun run dev
    depends_on:
      - backend

  docs:
    ports:
      - "6006:6006"
    environment:
      - NODE_ENV=development
    command: bun run storybook

  # Development-specific services
  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=dev_db
      - POSTGRES_USER=dev_user
      - POSTGRES_PASSWORD=dev_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    networks:
      - app-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - app-network

  # Optional: Database admin tool for development
  adminer:
    image: adminer:latest
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - app-network

volumes:
  postgres_dev_data:
