# Base Docker Compose configuration
# This file contains shared services and configurations
version: '3.8'

services:
  backend:
    build:
      context: ./apps/backend
      dockerfile: Dockerfile
    volumes:
      - ./apps/backend/src:/app/src
    networks:
      - app-network

  frontend:
    build:
      context: ./apps/frontend
      dockerfile: Dockerfile
    volumes:
      - ./apps/frontend/src:/app/src
      - ./apps/frontend/public:/app/public
    networks:
      - app-network

  docs:
    build:
      context: ./apps/docs
      dockerfile: Dockerfile
    volumes:
      - ./apps/docs/src:/app/src
      - ./apps/docs/public:/app/public
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  node_modules_backend:
  node_modules_frontend:
  node_modules_docs:
