# use the official Bun image
# see all versions at https://hub.docker.com/r/oven/bun/tags
FROM oven/bun:latest@sha256:a02c6162266611419fd84c8f96dbdbf3029532e2491314dee5172a27223e5428

WORKDIR /app

COPY bun.lockb package.json ./
COPY packages ./packages
COPY apps/frontend ./apps/frontend

RUN bun install

CMD ["bun", "run", "--cwd", "apps/frontend", "dev"]
